# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
spring:
  profiles:
    active: dev
  application:
    name: gatherfriends-back
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gatherfirends?serverTimezone=Asia/Shanghai
    username: root
    password: 524620LY
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
    # Spring Data Redis 配置
  data:
    redis:
      host: 192.168.229.130
      port: 6379
      password: 1234
      database: 3
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
    # 自定义Redis配置（用于Redisson）
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
      # 全局默认类型处理器（可选，针对所有 JSON 类型字段）
    default-type-handler: com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler
    # 扫描类型处理器所在的包（确保 MyBatis 能加载到 JacksonTypeHandler）
    type-handlers-package: com.baomidou.mybatisplus.extension.handlers

#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
