# 线上配置文件
# 注意开源时这个文件不要提交、或者不要填真实配置
spring:
  # DataSource Config
  ai:
    dashscope:
      chat:
        options:
          model: qwen-plus
      api-key: sk-1d86094764d645afab75b3b4ca7f0956
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gatherfirends
    username: root
    password: 524620LY
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
